### ISSUE TITLE
compile fail...

### ISSUE THREAD

**Issue by arizaini** [Haseo97/GCC-9.0.1#1]
i had problem while compile using this gcc... actually all gcc8 ~ 9, [this](https://gist.githubusercontent.com/arizaini/ec4ca008814d4c9aee3db165adc62e2d/raw/e16470d0c5aaed9c04fc3e9aa2623d18c09dc52c/gcc.txt) the log

currently OS: Ubuntu 16.04.6 LTS

**Comment by Haseo97** [comment]
Working fine here, can i see your build script?

**Comment by arizaini** [comment]
sure... [here](https://gist.githubusercontent.com/arizaini/af7db1e4125f99e66f1e5a71f6cae634/raw/32d8f713cd2a8eca75cb62f1c85eb4deef5fe531/bu.txt)

**Comment by Haseo97** [comment]
Okay,
Can you update your ubuntu to 18.04.xx and see how it goes please?

**Comment by arizaini** [comment]
maybe later i can update it..., what os you are using?

**Comment by Haseo97** [comment]
I'm running 18.04.2 LTS

**Comment by arizaini** [comment]
well thanks for your fast respone... i will update my OS later and tell you the result

**Comment by Haseo97** [comment]
Np, i'll wait for the result. Thanks!

**Comment by arizaini** [comment]
same error... [log](https://gist.githubusercontent.com/arizaini/720be6d69768726585450a33e9ebd106/raw/e2bac3e71367f1916f2da0a0924370a7fc81c250/log.txt)

OS: Linux Mint 19.1 Tessa

**Comment by Haseo97** [comment]
> same error... [log](https://gist.githubusercontent.com/arizaini/720be6d69768726585450a33e9ebd106/raw/e2bac3e71367f1916f2da0a0924370a7fc81c250/log.txt)
> kernel: [source](https://github.com/android-linux-stable/msm-3.18.git) only for test build
> config: msm8937_defconfig
> OS: Linux Mint 19.1 Tessa

Use this `[source](https://github.com/ryan-andri/android_kernel_xiaomi_santoni)` as your base.

**Comment by arizaini** [comment]
the result will same i guess

**Comment by Haseo97** [comment]
I tried already and work fine.

**Comment by arizaini** [comment]
hmm... did i missing something during setup environment?? btw i'm using [this](https://github.com/akhilnarang/scripts/blob/master/setup/android_build_env.sh) script

**Comment by Haseo97** [comment]
Try to install git-lfs to your environment.

**Comment by Haseo97** [comment]
And then redownload my gcc 9 repo

**Comment by arizaini** [comment]
> And then redownload my gcc 9 repo

using git clone or?

**Comment by Haseo97** [comment]
> > And then redownload my gcc 9 repo
> 
> using git clone or?

Git clone

**Comment by arizaini** [comment]
it works i guess..., is this `Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler` message appear while you compile on your machine?

now another [error](https://gist.githubusercontent.com/arizaini/63fec8c8d3b2183395d314c92b7fb7a0/raw/912a811f0c9620552cbf08de0970ed23077d7611/log1.txt)

**Comment by Haseo97** [comment]
> it works i guess..., is this `Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler` message appear while you compile on your machine?
> 
> now another [error](https://gist.githubusercontent.com/arizaini/63fec8c8d3b2183395d314c92b7fb7a0/raw/912a811f0c9620552cbf08de0970ed23077d7611/log1.txt)

Nope it didn't appear at all, might be source not compatible with gcc 9. 
Ryan's source is fully compatible with it.

**Comment by arizaini** [comment]
using ryan source pie-google config treble one, git-lfs is installed, but [this](https://gist.githubusercontent.com/arizaini/63fec8c8d3b2183395d314c92b7fb7a0/raw/912a811f0c9620552cbf08de0970ed23077d7611/log1.txt) error still appear..., any solution sir? thanks

**Comment by Haseo97** [comment]
No idea then, all is working fine here without any problems while compiling using Ryan's source.

**Comment by Haseo97** [comment]
I'll close the issues as i've tried it already and no issues spotted on me.
